version: '3.9'
services:
  server:
    build: .
    ports:
      - "8090:8090"
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DB_Project
    ports:
      - "5433:5432"

